---
- name: Create directory for docker-compose
  ansible.builtin.file:
    path: "{{ github_runner_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ github_runner_install_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0600'
  notify: Restart github runner

- name: Deploy github runner with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ github_runner_install_dir }}"
    state: present
    recreate: auto
    remove_orphans: true
  register: github_runner_deploy
