---
# Image Docker du runner GitLab
gitlab_runner_image: "gitlab/gitlab-runner"
gitlab_runner_image_tag: "v17.8.3"

# Configuration du runner
gitlab_runner_url: "https://gitlab.com"
gitlab_runner_name: "homelab-runner"
gitlab_runner_tags: "self-hosted,linux,docker,homelab"
gitlab_runner_run_untagged: "false"
gitlab_runner_locked: "false"

# Executor configuration
gitlab_runner_executor: "docker"
gitlab_runner_docker_image: "alpine:latest"
gitlab_runner_docker_privileged: false
gitlab_runner_docker_volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "/cache"

# Concurrency
gitlab_runner_concurrent: 4
gitlab_runner_check_interval: 0

# Repertoire d'installation sur l'hote
gitlab_runner_install_dir: "/opt/gitlab-runner"
