---
# Image Docker du runner GitHub Actions
github_runner_image: "myoung34/github-runner"
github_runner_image_tag: "2.332.0"
github_runner_image_digest: "sha256:557480d294e457f3bbb108819642e6794d839fe395850c221471752561e65aa6"

# Configuration du runner
github_runner_org_name: "TiPunchLabs"
github_runner_name_prefix: "homelab"
github_runner_labels: "self-hosted,linux,docker,homelab"
github_runner_group: "Default"
github_runner_work_dir: "/tmp/runner/work"

# Comportement du runner
github_runner_ephemeral: "false"
github_runner_disable_auto_update: "true"
github_runner_run_as_root: "true"

# Repertoire d'installation sur l'hote
github_runner_install_dir: "/opt/github-runner"
